FROM node:20-alpine

WORKDIR /app

# install deps with cache reuse
COPY package.json package-lock.json ./
RUN npm ci

# copy source after dependencies
COPY vite.config.ts ./vite.config.ts
COPY index.html ./index.html
COPY src ./src
COPY hr ./hr

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]


