FROM node:20-alpine
WORKDIR /app
COPY package.json /app/package.json
COPY vite.config.ts /app/vite.config.ts
COPY src /app/src
COPY index.html /app/index.html
RUN npm install
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]


